baseURL = "https://liqiduan.github.io/home/"
languageCode = "en-us"
title = "Liqiduan's Home"
theme = "travelify"
publicdir = "./"

[params]
  description = "Welcome to Liqiduan's home, here is the trace of my steps over the world."
